"""3.3

Revision ID: 8b30a6f10da5
Revises: cabe9318b206
Create Date: 2024-05-10 22:04:41.616377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b30a6f10da5'
down_revision: Union[str, None] = 'cabe9318b206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('objects_name_key', 'objects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('objects_name_key', 'objects', ['name'])
    # ### end Alembic commands ###
