"""added new field is_active in user file model

Revision ID: 5d0a19060366
Revises: 787ced6e2a33
Create Date: 2024-02-27 13:36:19.651770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0a19060366'
down_revision: Union[str, None] = '787ced6e2a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_files', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_files', 'is_active')
    # ### end Alembic commands ###
