"""added new field is_active in file model

Revision ID: 787ced6e2a33
Revises: a4d964a0cf7d
Create Date: 2024-02-27 02:32:12.896816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787ced6e2a33'
down_revision: Union[str, None] = 'a4d964a0cf7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_active')
    # ### end Alembic commands ###
