"""added new field 'is_favourite' in Object model

Revision ID: b548a29fd293
Revises: fe36ab5a33f4
Create Date: 2024-03-01 02:16:40.822939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b548a29fd293'
down_revision: Union[str, None] = 'fe36ab5a33f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('is_favourite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'is_favourite')
    # ### end Alembic commands ###
