"""deleted is favourite field in object model

Revision ID: bbb0340cd963
Revises: 009fd47911ec
Create Date: 2024-03-01 04:10:27.037401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb0340cd963'
down_revision: Union[str, None] = '009fd47911ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'is_favourite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('is_favourite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
